/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicResultsRouteImport } from './routes/api/public/results'
import { Route as ApiPublicSignalsRouteImport } from './routes/api/public/signals'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResultsRoute = ApiPublicResultsRouteImport.update({
  id: '/api/public/results',
  path: '/api/public/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSignalsRoute = ApiPublicSignalsRouteImport.update({
  id: '/api/public/signals',
  path: '/api/public/signals',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/results': typeof ApiPublicResultsRoute
  '/api/public/signals': typeof ApiPublicSignalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/results': typeof ApiPublicResultsRoute
  '/api/public/signals': typeof ApiPublicSignalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/results': typeof ApiPublicResultsRoute
  '/api/public/signals': typeof ApiPublicSignalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/results' | '/api/public/signals'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/results' | '/api/public/signals'
  id: '__root__' | '/' | '/api/public/results' | '/api/public/signals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicResultsRoute: typeof ApiPublicResultsRoute
  ApiPublicSignalsRoute: typeof ApiPublicSignalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/results': {
      id: '/api/public/results'
      path: '/api/public/results'
      fullPath: '/api/public/results'
      preLoaderRoute: typeof ApiPublicResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/signals': {
      id: '/api/public/signals'
      path: '/api/public/signals'
      fullPath: '/api/public/signals'
      preLoaderRoute: typeof ApiPublicSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicResultsRoute: ApiPublicResultsRoute,
  ApiPublicSignalsRoute: ApiPublicSignalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
